# Open-source edition branding (default).
set(ANON_EFFECT_NAME "Multi-Layer Anonymizer")
set(ANON_CATEGORY "Aagedal")
set(ANON_MATCH_NAME "AGDL Multi-Layer Anonymizer")
set(ANON_BUNDLE_BASE "Anonymizer")
set(ANON_APP_NAME "Multi-Layer Anonymizer")
set(ANON_PKG_BASENAME "MultiLayerAnonymizer")
set(ANON_PKG_TITLE "Multi-Layer Anonymizer")
set(ANON_ID_PREMIERE "me.aagedal.premiere.anonymizer")
set(ANON_ID_OFX "me.aagedal.ofx.anonymizer")
set(ANON_ID_FCP_APP "me.aagedal.fxplug.anonymizer")
set(ANON_ID_FCP_SERVICE "me.aagedal.fxplug.anonymizer.service")
set(ANON_OFX_PLUGIN_ID "me.aagedal.ofx.MultiLayerAnonymizer")
set(ANON_FX_GROUP_UUID "83F8AD9D-AC27-40C2-A111-0BFAA17AA9A7")
set(ANON_FX_PLUGIN_UUID "211035B9-C3CF-42E6-B8CB-F9C28DC3B98A")
